import test from "node:test";
import assert from "node:assert";
import { detectAdapterCapabilities } from "../src/core/adapterCapabilities.js";
test("Adapter Capabilities Detection Test", async () => {
  const caps = await detectAdapterCapabilities();
  assert.ok(caps.soffice);
  assert.strictEqual(typeof caps.soffice.available, "boolean");
  assert.strictEqual(caps.soffice.name, "LibreOffice (soffice)");
  assert.strictEqual(caps.soffice.required, false);
  assert.strictEqual(caps.soffice.mode, "optional-system-adapter");
  assert.ok(caps.soffice.formats.includes("doc"));
  assert.ok(caps.soffice.formats.includes("wps"));
  assert.ok(caps.soffice.fallback);
  assert.ok(caps.soffice.sendGateImpact);
  assert.ok(caps.soffice.purpose);
  assert.ok(caps.pandoc);
  assert.strictEqual(typeof caps.pandoc.available, "boolean");
  assert.strictEqual(caps.pandoc.name, "Pandoc");
  assert.strictEqual(caps.pandoc.required, false);
  assert.strictEqual(caps.pandoc.mode, "optional-system-adapter");
  assert.ok(caps.pandoc.formats.includes("html"));
  assert.ok(caps.pandoc.fallback);
  assert.ok(caps.pandoc.purpose);
  assert.ok(caps.tesseract);
  assert.strictEqual(typeof caps.tesseract.available, "boolean");
  assert.strictEqual(caps.tesseract.name, "Tesseract OCR");
  assert.strictEqual(caps.tesseract.required, false);
  assert.strictEqual(caps.tesseract.mode, "optional-system-adapter");
  assert.ok(caps.tesseract.formats.includes("pdf"));
  assert.ok(caps.tesseract.sendGateImpact.includes("Send Gate"));
  assert.ok(caps.tesseract.purpose);
  assert.ok(caps.pdfplumber);
  assert.strictEqual(typeof caps.pdfplumber.available, "boolean");
  assert.strictEqual(caps.pdfplumber.required, false);
  assert.ok(caps.pdfplumber.formats.includes("pdf"));
  assert.ok(caps.pdfplumber.purpose.includes("layout"));
  assert.ok(caps.pdftoppm);
  assert.strictEqual(typeof caps.pdftoppm.available, "boolean");
  assert.strictEqual(caps.pdftoppm.required, false);
  assert.ok(caps.pdftoppm.formats.includes("pdf"));
  assert.ok(caps.pdfOcr);
  assert.strictEqual(typeof caps.pdfOcr.available, "boolean");
  assert.strictEqual(caps.pdfOcr.required, false);
  assert.strictEqual(typeof caps.pdfOcr.components.tesseract, "boolean");
  assert.strictEqual(typeof caps.pdfOcr.components.pdftoppm, "boolean");
  assert.strictEqual(typeof caps.pdfOcr.components.pdfinfo, "boolean");
  assert.ok(caps.marker);
  assert.strictEqual(typeof caps.marker.available, "boolean");
  assert.strictEqual(caps.marker.required, false);
  assert.ok(caps.marker.formats.includes("latex"));
});
